apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-simulator
  template:
    metadata:
      labels:
        app: apc-simulator
    spec:
      containers:
        - name: apc-simulator
          image: takidog/apc:latest
          ports:
            - containerPort: 3031
          env:
            - name: NATS_SERVICE_CONNECTION
              value: 'nats-server:4222'
            - name: MONGODB_CONNECTION
              value: 'mongodb://mongodb:27017'
            - name: MONGODB_DB_NAME
              value: 'TSMC'
