apiVersion: v1
kind: Service
metadata:
  name: apc-simulator
spec:
  type: NodePort
  selector:
    app: apc-simulator
  ports:
    - name: http
      port: 3031
      protocol: TCP
      targetPort: 3031