name: Unit test Coverage

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
  workflow_dispatch:

jobs:
  JS-Unit-Test-Coverage:
    name: JS-Unit-Test Coverage
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
